/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
   return {
      name: 'openspec-archive-change',
      description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
      instructions: `Archive a completed change in the experimental workflow.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec-hw status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Assess delta spec sync state**

   Check for delta specs at \`openspec/changes/<name>/specs/\`. If none exist, proceed without sync prompt.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec at \`openspec/specs/<capability>/spec.md\`
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   If user chooses sync, use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke openspec-sync-specs for change '<name>'. Delta spec analysis: <include the analyzed delta spec summary>"). Proceed to archive regardless of choice.

4b. **Spec Blast Radius Review** (if spec-blast-radius.md exists)

   Check for \`openspec/changes/<name>/spec-blast-radius.md\`.
   If it doesn't exist: note "No blast radius file found — skipping impact review." and proceed.
   If the file exists but its Summary says "No existing specs impacted": note that and proceed.

   **If blast radius file exists and has impacted specs:**

   Read the file and extract all entries under "## Impacted Specs".
   For each entry, collect: spec path, impact level, impacted requirements list.

   Display a triage table to the user:

   \`\`\`
   ## Spec Impact Review

   This change impacted the following existing specs. Please decide what action to take for each.

   | # | Spec | Impact | Requirements Affected |
   |---|------|--------|----------------------|
   | 1 | openspec/specs/auth/spec.md | High | Session expiry, Token refresh |
   | 2 | openspec/specs/payments/spec.md | Medium | Checkout flow |
   \`\`\`

   Then, for each impacted spec, use the **AskUserQuestion tool** with these options:
   - **"Sync now"** — delegate spec merge to openspec-sync-specs
   - **"Mark for review"** — add a review notice to the spec file
   - **"Skip"** — no action for this spec

   Process each selected action:

   - **Sync now**: Use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke
     openspec-sync-specs. Sync the spec at '<spec-path>' using the delta from change '<name>'.")
   - **Mark for review**: Read the spec file, prepend the following comment block at the very top,
     then write it back:
     \`\`\`markdown
     <!-- NEEDS REVIEW
     Impacted by change: <change-name>
     Date: <YYYY-MM-DD>
     Reason: <impact level> impact — <list impacted requirements>
     Run /opsx-hw:verify-spec to assess what needs updating.
     -->
     \`\`\`
   - **Skip**: Take no action on this spec.

   Track triage results for the archive summary (e.g. "2 synced, 1 marked for review, 0 skipped").

5. **Perform the archive**

   Create the archive directory if it doesn't exist:
   \`\`\`bash
   mkdir -p openspec/changes/archive
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move the change directory to archive

   \`\`\`bash
   mv openspec/changes/<name> openspec/changes/archive/YYYY-MM-DD-<name>
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Whether specs were synced (if applicable)
   - Blast radius triage results (e.g. "2 specs synced, 1 marked for review" or "No blast radius")
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** openspec/changes/archive/YYYY-MM-DD-<name>/
**Delta specs:** ✓ Synced to main specs (or "No delta specs" or "Sync skipped")
**Blast radius:** 2 spec(s) synced, 1 marked for review (or "No impacted specs" or "No blast radius file")

All artifacts complete. All tasks complete.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec-hw status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, use openspec-sync-specs approach (agent-driven)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- If spec-blast-radius.md does not exist, skip step 4b silently (no warning needed)`,
      license: 'MIT',
      compatibility: 'Requires openspec-hw CLI.',
      metadata: { author: 'openspec', version: '1.0' },
   };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
   return {
      name: 'OPSX: Archive',
      description: 'Archive a completed change in the experimental workflow',
      category: 'Workflow',
      tags: ['workflow', 'archive', 'experimental'],
      content: `Archive a completed change in the experimental workflow.

**Input**: Optionally specify a change name after \`/opsx-hw:archive\` (e.g., \`/opsx-hw:archive add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec-hw status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Prompt user for confirmation to continue
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Assess delta spec sync state**

   Check for delta specs at \`openspec/changes/<name>/specs/\`. If none exist, proceed without sync prompt.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec at \`openspec/specs/<capability>/spec.md\`
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

   **Prompt options:**
   - If changes needed: "Sync now (recommended)", "Archive without syncing"
   - If already synced: "Archive now", "Sync anyway", "Cancel"

   If user chooses sync, use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke openspec-sync-specs for change '<name>'. Delta spec analysis: <include the analyzed delta spec summary>"). Proceed to archive regardless of choice.

4b. **Spec Blast Radius Review** (if spec-blast-radius.md exists)

   Check for \`openspec/changes/<name>/spec-blast-radius.md\`.
   If it doesn't exist: note "No blast radius file found — skipping impact review." and proceed.
   If the file exists but its Summary says "No existing specs impacted": note that and proceed.

   **If blast radius file exists and has impacted specs:**

   Read the file and extract all entries under "## Impacted Specs".
   For each entry, collect: spec path, impact level, impacted requirements list.

   Display a triage table to the user:

   \`\`\`
   ## Spec Impact Review

   This change impacted the following existing specs. Please decide what action to take for each.

   | # | Spec | Impact | Requirements Affected |
   |---|------|--------|----------------------|
   | 1 | openspec/specs/auth/spec.md | High | Session expiry, Token refresh |
   | 2 | openspec/specs/payments/spec.md | Medium | Checkout flow |
   \`\`\`

   Then, for each impacted spec, use the **AskUserQuestion tool** with these options:
   - **"Sync now"** — delegate spec merge to openspec-sync-specs
   - **"Mark for review"** — add a review notice to the spec file
   - **"Skip"** — no action for this spec

   Process each selected action:

   - **Sync now**: Use Task tool (subagent_type: "general-purpose", prompt: "Use Skill tool to invoke
     openspec-sync-specs. Sync the spec at '<spec-path>' using the delta from change '<name>'.")
   - **Mark for review**: Read the spec file, prepend the following comment block at the very top,
     then write it back:
     \`\`\`markdown
     <!-- NEEDS REVIEW
     Impacted by change: <change-name>
     Date: <YYYY-MM-DD>
     Reason: <impact level> impact — <list impacted requirements>
     Run /opsx-hw:verify-spec to assess what needs updating.
     -->
     \`\`\`
   - **Skip**: Take no action on this spec.

   Track triage results for the archive summary (e.g. "2 synced, 1 marked for review, 0 skipped").

5. **Perform the archive**

   Create the archive directory if it doesn't exist:
   \`\`\`bash
   mkdir -p openspec/changes/archive
   \`\`\`

   Generate target name using current date: \`YYYY-MM-DD-<change-name>\`

   **Check if target already exists:**
   - If yes: Fail with error, suggest renaming existing archive or using different date
   - If no: Move the change directory to archive

   \`\`\`bash
   mv openspec/changes/<name> openspec/changes/archive/YYYY-MM-DD-<name>
   \`\`\`

6. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Spec sync status (synced / sync skipped / no delta specs)
   - Blast radius triage results (e.g. "2 specs synced, 1 marked for review" or "No blast radius")
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** openspec/changes/archive/YYYY-MM-DD-<name>/
**Delta specs:** ✓ Synced to main specs
**Blast radius:** 2 spec(s) synced, 1 marked for review (or "No impacted specs")

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (No Delta Specs)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** openspec/changes/archive/YYYY-MM-DD-<name>/
**Delta specs:** No delta specs
**Blast radius:** No impacted specs (or triage results if blast radius file exists)

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success With Warnings**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** openspec/changes/archive/YYYY-MM-DD-<name>/
**Delta specs:** Sync skipped (user chose to skip)
**Blast radius:** 1 marked for review, 1 skipped

**Warnings:**
- Archived with 2 incomplete artifacts
- Archived with 3 incomplete tasks
- Delta spec sync was skipped (user chose to skip)

Review the archive if this was not intentional.
\`\`\`

**Output On Error (Archive Exists)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Target:** openspec/changes/archive/YYYY-MM-DD-<name>/

Target archive directory already exists.

**Options:**
1. Rename the existing archive
2. Delete the existing archive if it's a duplicate
3. Wait until a different date to archive
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec-hw status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, use the Skill tool to invoke \`openspec-sync-specs\` (agent-driven)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- If spec-blast-radius.md does not exist, skip step 4b silently (no warning needed)`
   };
}
