/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const INSTRUCTIONS = `Verify and fix use case traceability across all artifacts for a change.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only changes that have a \`usecases.md\` artifact (traceability mapping requires it).

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Load artifacts**

   \`\`\`bash
   openspec-hw instructions apply --change "<name>" --json
   \`\`\`

   From the returned \`contextFiles\`, read:
   - \`usecases.md\` — **required**; abort with a clear message if missing
   - \`specs/**/*.md\` — optional
   - \`design.md\` — optional
   - \`tasks.md\` — optional

3. **Parse ground-truth steps from usecases.md**

   For each use case section (e.g., \`## Use Case 1: …\`):

   - **Main scenario steps**: numbered lines such as \`1. Actor does X\` → ID \`UCn-Sm\` (e.g., \`UC1-S1\`, \`UC1-S2\`)
   - **Extension steps**: lines like \`2a.\`, \`3b.\` → ID \`UCn-Ema\` (e.g., \`UC1-E2a\`, \`UC1-E3b\`)

   Capture the **exact prose** of each step. This is the canonical description.

   Step ID format rules (strict):
   - Use \`UC\` + use-case number + \`-\` + \`S\` + step number for main steps: \`UC1-S3\`
   - Use \`UC\` + use-case number + \`-\` + \`E\` + step number + letter for extensions: \`UC1-E2a\`
   - Never use spaces: \`UC 1-S3\` is wrong.

4. **Verify the Traceability Mapping table in usecases.md**

   Locate the "Use Case Traceability Mapping" table (heading: \`## Use Case Traceability Mapping\` or similar).

   For each ground-truth step:
   - **Missing row** → insert a new row in step-ID order
   - **Inaccurate description** → replace with the exact prose from ground truth
   - **Phantom row** (step ID has no matching use case step) → remove the row

   Write the corrected \`usecases.md\` back to disk if any changes were made.

5. **Verify specs** (for each file in \`specs/**/*.md\` if present)

   a. **Preamble block** — look for a \`## Use Case Traceability\` (or similar) section at the top of the spec.
      - For every step in the traceability table: ensure the step appears here with its canonical description.
      - Fix phantom/inaccurate entries; add missing ones.

   b. **Requirement annotations** — look for \`**Implements**: UCn-Sm - description\` lines inside requirement sections.
      - Phantom annotation (step ID does not exist) → remove the annotation.
      - Inaccurate description → replace with canonical text from the mapping table.
      - Missing coverage: if a ground-truth step is not referenced anywhere in this spec and it is relevant to the spec's capability, add \`**Implements**: UCn-Sm - <canonical description>\` to the nearest relevant requirement. If no requirement fits, add a TODO comment: \`<!-- TODO: cover UC1-S3 - <description> -->\`.

   Write the corrected spec file back to disk if any changes were made.

6. **Verify design.md** (if present)

   Look for \`**Addresses**: UCn-Sm - description\` lines.
   - Phantom → remove.
   - Inaccurate description → fix to canonical text.
   - Missing step → add \`**Addresses**: UCn-Sm - <canonical description>\` to the nearest relevant design section. If no section fits, append a \`## Use Case Coverage\` section listing uncovered steps.

   Write the corrected \`design.md\` back to disk if any changes were made.

7. **Verify tasks.md** (if present)

   Look for \`(Addresses: UCn-Sm)\` or \`(Addresses: UCn-Sm, UCn-Sn)\` annotations on task lines.
   - Phantom step ID in annotation → remove that ID from the annotation (or remove the whole annotation if it becomes empty).
   - Missing step → add the annotation to the nearest relevant task. If no task fits, add a new task: \`- [ ] Address UC1-S3 - <canonical description> (Addresses: UC1-S3)\`.

   Write the corrected \`tasks.md\` back to disk if any changes were made.

8. **Never create files** that do not already exist. Only edit existing artifacts.

9. **Print verification report**

   \`\`\`
   ## Traceability Verification Report: <change-name>

   ### Ground Truth
   - Use cases found: N
   - Total steps (main + extensions): M

   ### usecases.md
   - Rows added: X  |  Rows fixed: Y  |  Phantom rows removed: Z

   ### specs/<name>/spec.md  (one section per spec file)
   - Preamble entries fixed: X
   - Requirement annotations: added N, fixed M, removed Z phantom(s)

   ### design.md
   - Annotations: added N, fixed M, removed Z phantom(s)

   ### tasks.md
   - Annotations: added N, removed Z phantom(s)

   ### Result
   All traceability annotations are consistent.  ✓
   — or —
   Could not fully resolve: <list unresolvable items>
   \`\`\`

**Key rules**

- Descriptions in annotations **must match canonical text exactly** (copy from table, do not paraphrase).
- Step IDs must be exact: \`UC1-S1\`, not \`UC 1-S1\`, not \`uc1-s1\`.
- Only annotate steps that genuinely belong to the artifact; do not force every step into every file.
- Do NOT create new artifact files; only patch files that already exist.`;

export function getVerifySpecSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-spec',
    description: 'Verify and fix use case traceability across all artifacts. Use when the user wants to audit or repair traceability annotations in usecases.md, specs, design.md, or tasks.md.',
    instructions: INSTRUCTIONS,
    license: 'MIT',
    compatibility: 'Requires openspec-hw CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifySpecCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify Spec',
    description: 'Verify and fix use case traceability across all artifacts',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'traceability', 'experimental'],
    content: `Verify and fix use case traceability across all artifacts for a change.

**Input**: Optionally specify a change name after \`/opsx-hw:verify-spec\` (e.g., \`/opsx-hw:verify-spec add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only changes that have a \`usecases.md\` artifact (traceability mapping requires it).

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Load artifacts**

   \`\`\`bash
   openspec-hw instructions apply --change "<name>" --json
   \`\`\`

   From the returned \`contextFiles\`, read:
   - \`usecases.md\` — **required**; abort with a clear message if missing
   - \`specs/**/*.md\` — optional
   - \`design.md\` — optional
   - \`tasks.md\` — optional

3. **Parse ground-truth steps from usecases.md**

   For each use case section (e.g., \`## Use Case 1: …\`):

   - **Main scenario steps**: numbered lines such as \`1. Actor does X\` → ID \`UCn-Sm\` (e.g., \`UC1-S1\`, \`UC1-S2\`)
   - **Extension steps**: lines like \`2a.\`, \`3b.\` → ID \`UCn-Ema\` (e.g., \`UC1-E2a\`, \`UC1-E3b\`)

   Capture the **exact prose** of each step. This is the canonical description.

   Step ID format rules (strict):
   - Use \`UC\` + use-case number + \`-\` + \`S\` + step number for main steps: \`UC1-S3\`
   - Use \`UC\` + use-case number + \`-\` + \`E\` + step number + letter for extensions: \`UC1-E2a\`
   - Never use spaces: \`UC 1-S3\` is wrong.

4. **Verify the Traceability Mapping table in usecases.md**

   Locate the "Use Case Traceability Mapping" table (heading: \`## Use Case Traceability Mapping\` or similar).

   For each ground-truth step:
   - **Missing row** → insert a new row in step-ID order
   - **Inaccurate description** → replace with the exact prose from ground truth
   - **Phantom row** (step ID has no matching use case step) → remove the row

   Write the corrected \`usecases.md\` back to disk if any changes were made.

5. **Verify specs** (for each file in \`specs/**/*.md\` if present)

   a. **Preamble block** — look for a \`## Use Case Traceability\` (or similar) section at the top of the spec.
      - For every step in the traceability table: ensure the step appears here with its canonical description.
      - Fix phantom/inaccurate entries; add missing ones.

   b. **Requirement annotations** — look for \`**Implements**: UCn-Sm - description\` lines inside requirement sections.
      - Phantom annotation (step ID does not exist) → remove the annotation.
      - Inaccurate description → replace with canonical text from the mapping table.
      - Missing coverage: if a ground-truth step is not referenced anywhere in this spec and it is relevant to the spec's capability, add \`**Implements**: UCn-Sm - <canonical description>\` to the nearest relevant requirement. If no requirement fits, add a TODO comment: \`<!-- TODO: cover UC1-S3 - <description> -->\`.

   Write the corrected spec file back to disk if any changes were made.

6. **Verify design.md** (if present)

   Look for \`**Addresses**: UCn-Sm - description\` lines.
   - Phantom → remove.
   - Inaccurate description → fix to canonical text.
   - Missing step → add \`**Addresses**: UCn-Sm - <canonical description>\` to the nearest relevant design section. If no section fits, append a \`## Use Case Coverage\` section listing uncovered steps.

   Write the corrected \`design.md\` back to disk if any changes were made.

7. **Verify tasks.md** (if present)

   Look for \`(Addresses: UCn-Sm)\` or \`(Addresses: UCn-Sm, UCn-Sn)\` annotations on task lines.
   - Phantom step ID in annotation → remove that ID from the annotation (or remove the whole annotation if it becomes empty).
   - Missing step → add the annotation to the nearest relevant task. If no task fits, add a new task: \`- [ ] Address UC1-S3 - <canonical description> (Addresses: UC1-S3)\`.

   Write the corrected \`tasks.md\` back to disk if any changes were made.

8. **Never create files** that do not already exist. Only edit existing artifacts.

9. **Print verification report**

   \`\`\`
   ## Traceability Verification Report: <change-name>

   ### Ground Truth
   - Use cases found: N
   - Total steps (main + extensions): M

   ### usecases.md
   - Rows added: X  |  Rows fixed: Y  |  Phantom rows removed: Z

   ### specs/<name>/spec.md  (one section per spec file)
   - Preamble entries fixed: X
   - Requirement annotations: added N, fixed M, removed Z phantom(s)

   ### design.md
   - Annotations: added N, fixed M, removed Z phantom(s)

   ### tasks.md
   - Annotations: added N, removed Z phantom(s)

   ### Result
   All traceability annotations are consistent.  ✓
   — or —
   Could not fully resolve: <list unresolvable items>
   \`\`\`

**Key rules**

- Descriptions in annotations **must match canonical text exactly** (copy from table, do not paraphrase).
- Step IDs must be exact: \`UC1-S1\`, not \`UC 1-S1\`, not \`uc1-s1\`.
- Only annotate steps that genuinely belong to the artifact; do not force every step into every file.
- Do NOT create new artifact files; only patch files that already exist.`,
  };
}
