/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
   return {
      name: 'synergyspec-verify-change',
      description: 'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
      instructions: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`synergyspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   synergyspec-hw status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. **Get the change directory and load artifacts**

   \`\`\`bash
   synergyspec-hw instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If tasks.md exists in contextFiles, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`synergyspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If design.md exists in contextFiles:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

9. **Spec Impact Analysis — Generate Blast Radius**

   This step identifies which existing specs in \`synergyspec/specs/\` are affected
   by the code changes made for this change. Run it after the Verification Report.

   **9a. Get changed files via git diff**

   Run:
   \`\`\`bash
   git diff --name-only $(git merge-base HEAD main) HEAD
   \`\`\`
   If that fails (no \`main\` branch, detached HEAD, not a git repo), fall back to:
   \`\`\`bash
   git diff --name-only HEAD~1 HEAD
   \`\`\`
   If still no output or git is unavailable:
   - Note "No git diff available — skipping blast radius analysis."
   - Write a minimal \`spec-blast-radius.md\` with that note and stop this step.

   **9b. Build a keyword index from changed files**

   For each changed file path, extract:
   - Directory name segments (e.g. \`src/auth/session.ts\` → \`["auth", "session"]\`)
   - Exported symbol names: grep each changed file for \`export (function|class|const|type|interface) \\w+\`
   - Limit to the first 100 changed files to avoid runaway analysis.

   **9c. Scan all existing specs**

   Enumerate all files matching \`synergyspec/specs/**/*.md\`.
   If none found: note "No existing specs found — skipping blast radius analysis."

   For each spec file, extract:
   - **Capability name**: the parent folder name (e.g. \`synergyspec/specs/user-auth/spec.md\` → \`user-auth\`)
   - **Requirement names**: all lines matching \`### Requirement:\`
   - **UC step references**: all \`**Implements**: UCx-Sy\` patterns
   - **Keyword set**: all meaningful words (>4 chars) from requirement names and WHEN/THEN clauses

   **9d. Cross-reference and score each existing spec**

   Score each spec against the keyword index from 9b:

   - **High impact** (include in blast radius): any of:
     - A changed file path segment exactly matches the spec's capability name
       (e.g. changed file in \`src/user-auth/\` matches spec \`synergyspec/specs/user-auth/\`)
     - The change's own delta specs (in \`synergyspec/changes/<name>/specs/\`) contain
       \`**Implements**\` references (UCx-Sy IDs) that also appear in this existing spec
   - **Medium impact** (include in blast radius): 2 or more keywords from changed file
     path segments or exported symbols appear in the spec's requirement text or scenarios
   - **Low / No impact**: fewer than 2 keyword matches — exclude from blast radius

   **9e. Identify affected tests per impacted spec**

   For each High/Medium spec, check \`synergyspec/changes/<name>/spec-tests.md\` (if it exists).
   Look in the Requirement Traceability Matrix for rows where the "Requirement" column
   contains text matching the impacted requirement names. Collect the "Test Case" file paths
   from those rows.

   **9f. Write \`synergyspec/changes/<name>/spec-blast-radius.md\`**

   Use this format:

   \`\`\`markdown
   # Spec Blast Radius: <change-name>
   Generated: <ISO timestamp>

   ## Summary
   <N> spec(s) impacted by this change.

   ## Impacted Specs

   ### synergyspec/specs/<capability>/spec.md
   **Impact Level**: High
   **Reason**: Changed file \`src/<path>\` matches capability name "<capability>"
   **Impacted Requirements**:
   - Requirement: <name> (UC1-S4)
   - Requirement: <name> (UC1-S5)
   **Affected Tests**: \`test/session.test.ts\`, \`test/integration/auth.test.ts\`

   ### synergyspec/specs/<other>/spec.md
   **Impact Level**: Medium
   **Reason**: Keywords "auth", "token" from changed files match 3 requirements
   **Impacted Requirements**:
   - Requirement: <name>
   **Affected Tests**: (none mapped in spec-tests.md)

   ## Unimpacted Specs
   - synergyspec/specs/gallery/spec.md — no keyword overlap detected
   \`\`\`

   If no specs are impacted, write:

   \`\`\`markdown
   # Spec Blast Radius: <change-name>
   Generated: <ISO timestamp>

   ## Summary
   No existing specs impacted by this change.
   \`\`\`

   **9g. Append blast radius summary to the Verification Report**

   Add a final line to the report output:
   - If impacted: "📍 Blast radius: <N> spec(s) impacted → \`synergyspec/changes/<name>/spec-blast-radius.md\`"
   - If none: "📍 Blast radius: No existing specs impacted."
   - If skipped: "📍 Blast radius: Skipped (<reason>)."

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why
- If git diff unavailable or \`synergyspec/specs/\` is empty: skip blast radius gracefully

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"

**Knowledge Graph Integration (Optional)**

If KG is enabled (\`.synergyspec/kg/\` exists), use it as a structured ground truth for connectivity checks:

1. Initialize: \`const kg = createKGToolInterface(projectRoot);\`
2. Call \`kg:get-change-traceability\` with the changeId to get all entities and their relationships.
3. Cross-check the graph against the implementation:
   - Every Task should have at least one implementing CodeFile (\`implementedBy\`)
   - Every Requirement should have at least one testing TestCase (\`tests\`, inbound)
   - Flag orphans: entities without required relationships
4. Use \`analyzeBlastRadiusViaKG\` (from \`src/core/kg/blast-radius-utils.js\`) on changed files to find impacted specs via KG traversal.
5. Report KG coverage alongside file-based checks. On KG error, warn and fall back to file-based verification only.`,
      license: 'MIT',
      compatibility: 'Requires synergyspec-hw CLI.',
      metadata: { author: 'synergyspec', version: '1.0' },
   };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
   return {
      name: 'OPSX: Verify',
      description: 'Verify implementation matches change artifacts before archiving',
      category: 'Workflow',
      tags: ['workflow', 'verify', 'experimental'],
      content: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name after \`/synspec:verify\` (e.g., \`/synspec:verify add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`synergyspec-hw list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   synergyspec-hw status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. **Get the change directory and load artifacts**

   \`\`\`bash
   synergyspec-hw instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If tasks.md exists in contextFiles, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`synergyspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If design.md exists in contextFiles:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

9. **Spec Impact Analysis — Generate Blast Radius**

   This step identifies which existing specs in \`synergyspec/specs/\` are affected
   by the code changes made for this change. Run it after the Verification Report.

   **9a. Get changed files via git diff**

   Run:
   \`\`\`bash
   git diff --name-only $(git merge-base HEAD main) HEAD
   \`\`\`
   If that fails (no \`main\` branch, detached HEAD, not a git repo), fall back to:
   \`\`\`bash
   git diff --name-only HEAD~1 HEAD
   \`\`\`
   If still no output or git is unavailable:
   - Note "No git diff available — skipping blast radius analysis."
   - Write a minimal \`spec-blast-radius.md\` with that note and stop this step.

   **9b. Build a keyword index from changed files**

   For each changed file path, extract:
   - Directory name segments (e.g. \`src/auth/session.ts\` → \`["auth", "session"]\`)
   - Exported symbol names: grep each changed file for \`export (function|class|const|type|interface) \\w+\`
   - Limit to the first 100 changed files to avoid runaway analysis.

   **9c. Scan all existing specs**

   Enumerate all files matching \`synergyspec/specs/**/*.md\`.
   If none found: note "No existing specs found — skipping blast radius analysis."

   For each spec file, extract:
   - **Capability name**: the parent folder name (e.g. \`synergyspec/specs/user-auth/spec.md\` → \`user-auth\`)
   - **Requirement names**: all lines matching \`### Requirement:\`
   - **UC step references**: all \`**Implements**: UCx-Sy\` patterns
   - **Keyword set**: all meaningful words (>4 chars) from requirement names and WHEN/THEN clauses

   **9d. Cross-reference and score each existing spec**

   Score each spec against the keyword index from 9b:

   - **High impact** (include in blast radius): any of:
     - A changed file path segment exactly matches the spec's capability name
       (e.g. changed file in \`src/user-auth/\` matches spec \`synergyspec/specs/user-auth/\`)
     - The change's own delta specs (in \`synergyspec/changes/<name>/specs/\`) contain
       \`**Implements**\` references (UCx-Sy IDs) that also appear in this existing spec
   - **Medium impact** (include in blast radius): 2 or more keywords from changed file
     path segments or exported symbols appear in the spec's requirement text or scenarios
   - **Low / No impact**: fewer than 2 keyword matches — exclude from blast radius

   **9e. Identify affected tests per impacted spec**

   For each High/Medium spec, check \`synergyspec/changes/<name>/spec-tests.md\` (if it exists).
   Look in the Requirement Traceability Matrix for rows where the "Requirement" column
   contains text matching the impacted requirement names. Collect the "Test Case" file paths
   from those rows.

   **9f. Write \`synergyspec/changes/<name>/spec-blast-radius.md\`**

   Use this format:

   \`\`\`markdown
   # Spec Blast Radius: <change-name>
   Generated: <ISO timestamp>

   ## Summary
   <N> spec(s) impacted by this change.

   ## Impacted Specs

   ### synergyspec/specs/<capability>/spec.md
   **Impact Level**: High
   **Reason**: Changed file \`src/<path>\` matches capability name "<capability>"
   **Impacted Requirements**:
   - Requirement: <name> (UC1-S4)
   - Requirement: <name> (UC1-S5)
   **Affected Tests**: \`test/session.test.ts\`, \`test/integration/auth.test.ts\`

   ### synergyspec/specs/<other>/spec.md
   **Impact Level**: Medium
   **Reason**: Keywords "auth", "token" from changed files match 3 requirements
   **Impacted Requirements**:
   - Requirement: <name>
   **Affected Tests**: (none mapped in spec-tests.md)

   ## Unimpacted Specs
   - synergyspec/specs/gallery/spec.md — no keyword overlap detected
   \`\`\`

   If no specs are impacted, write:

   \`\`\`markdown
   # Spec Blast Radius: <change-name>
   Generated: <ISO timestamp>

   ## Summary
   No existing specs impacted by this change.
   \`\`\`

   **9g. Append blast radius summary to the Verification Report**

   Add a final line to the report output:
   - If impacted: "📍 Blast radius: <N> spec(s) impacted → \`synergyspec/changes/<name>/spec-blast-radius.md\`"
   - If none: "📍 Blast radius: No existing specs impacted."
   - If skipped: "📍 Blast radius: Skipped (<reason>)."

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why
- If git diff unavailable or \`synergyspec/specs/\` is empty: skip blast radius gracefully

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`
   };
}
