/**
 * Property-based tests for gridGeometry.ts — generated by /synspec:gen-tests
 * Framework: fast-check (TypeScript)
 * Generated: 2026-03-24
 *
 * Each test corresponds to one WHEN/THEN scenario in spec.md.
 */

import { describe, it } from 'vitest';
import * as fc from 'fast-check';
import {
  snapToCell,
  buildOccupancySet,
  isValidPlacement,
  resolveLayout,
  type WidgetLayout,
} from './gridGeometry';

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

const positiveInt = (max: number) => fc.integer({ min: 1, max });
const nonNegInt = (max: number) => fc.integer({ min: 0, max });

/** Widget that always fits within (cols × rows). */
const widgetArb = (cols: number, rows: number): fc.Arbitrary<WidgetLayout> =>
  fc.record({
    id: fc.uuid(),
    w: positiveInt(cols),
    h: positiveInt(rows),
  }).chain(({ id, w, h }) =>
    fc.record({
      id: fc.constant(id),
      x: nonNegInt(cols - w),
      y: nonNegInt(rows - h),
      w: fc.constant(w),
      h: fc.constant(h),
    })
  );

// ---------------------------------------------------------------------------
// UC2-S1 — "Valid initial layout renders correctly"
// WHEN DashboardGrid mounted with valid initialLayout
// THEN each widget rendered at declared position and span
// ---------------------------------------------------------------------------
describe('PBT UC2-S1: valid initial layout — widgets keep declared positions', () => {
  it('UC2-S1: resolveLayout returns same positions for non-conflicting layouts', () => {
    // Build a layout where widgets are guaranteed non-overlapping by construction
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 8 }),
        fc.integer({ min: 2, max: 8 }),
        (cols, rows) => {
          // Single widget always valid if it fits
          const w = 1, h = 1, x = 0, y = 0;
          const layout: WidgetLayout[] = [{ id: 'a', x, y, w, h }];
          const resolved = resolveLayout(layout, cols, rows);
          return resolved[0].x === x && resolved[0].y === y;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-S1 — "Empty initial layout renders an empty grid"
// WHEN DashboardGrid mounted with empty initialLayout
// THEN no widgets rendered
// ---------------------------------------------------------------------------
describe('PBT UC2-S1: empty layout produces empty result', () => {
  it('UC2-S1: resolveLayout of empty input is always empty', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 12 }),
        fc.integer({ min: 1, max: 12 }),
        (cols, rows) => {
          const resolved = resolveLayout([], cols, rows);
          return resolved.length === 0;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-S2 — "Grid divided into correct columns and rows"
// WHEN DashboardGrid rendered with cols/rows props
// THEN grid has correct structure
// (Pure function property: snapToCell respects column count)
// ---------------------------------------------------------------------------
describe('PBT UC2-S2: snap never returns col >= cols or row >= rows', () => {
  it('UC2-S2: snapToCell col is always < cols when constraints provided', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 2000 }),
        fc.integer({ min: 0, max: 2000 }),
        fc.integer({ min: 1, max: 200 }),
        fc.integer({ min: 1, max: 12 }),
        fc.integer({ min: 1, max: 12 }),
        fc.integer({ min: 1, max: 6 }),
        fc.integer({ min: 1, max: 6 }),
        (px, py, cellSize, cols, rows, w, h) => {
          const safeW = Math.min(w, cols);
          const safeH = Math.min(h, rows);
          const { col, row } = snapToCell(px, py, cellSize, {
            w: safeW, h: safeH, cols, rows,
          });
          return col >= 0 && col + safeW <= cols && row >= 0 && row + safeH <= rows;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-S2 — "Cell size is configurable"
// WHEN rendered with cellSize prop
// THEN each cell at specified pixel dimension
// (Property: snapToCell result scales linearly with cellSize)
// ---------------------------------------------------------------------------
describe('PBT UC2-S2: snapToCell scales with cellSize', () => {
  it('UC2-S2: doubling cellSize halves the raw cell index (before clamping)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 1000 }),
        fc.integer({ min: 1, max: 1000 }),
        fc.integer({ min: 1, max: 100 }),
        (px, py, cellSize) => {
          const r1 = snapToCell(px, py, cellSize);
          const r2 = snapToCell(px * 2, py * 2, cellSize * 2);
          return r1.col === r2.col && r1.row === r2.row;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-S3 — "Widget spans declared columns and rows"
// WHEN widget w=N h=M at position x,y
// THEN occupies correct cells
// ---------------------------------------------------------------------------
describe('PBT UC2-S3: occupancy set always covers all widget cells', () => {
  it('UC2-S3: buildOccupancySet contains every cell of a widget', () => {
    fc.assert(
      fc.property(
        widgetArb(10, 10),
        (widget) => {
          const set = buildOccupancySet([widget]);
          for (let c = widget.x; c < widget.x + widget.w; c++) {
            for (let r = widget.y; r < widget.y + widget.h; r++) {
              if (!set.has(`${c},${r}`)) return false;
            }
          }
          return true;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-S4 — "Multiple widgets rendered without overlap"
// WHEN multiple non-overlapping widgets mounted
// THEN no two share a cell
// ---------------------------------------------------------------------------
describe('PBT UC2-S4: resolveLayout output never has overlapping widgets', () => {
  it('UC2-S4: no two resolved widgets occupy the same cell', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 3, max: 8 }),
        fc.integer({ min: 3, max: 8 }),
        // Use uniqueArray to guarantee distinct IDs; cap count to grid capacity
        fc.uniqueArray(fc.string({ minLength: 1, maxLength: 8 }), { minLength: 1, maxLength: 6 }),
        (cols, rows, ids) => {
          const input: WidgetLayout[] = ids.map((id) => ({ id, x: 0, y: 0, w: 1, h: 1 }));
          const resolved = resolveLayout(input, cols, rows);
          const occupied = new Set<string>();
          for (const w of resolved) {
            for (let c = w.x; c < w.x + w.w; c++) {
              for (let r = w.y; r < w.y + w.h; r++) {
                const key = `${c},${r}`;
                if (occupied.has(key)) return false;
                occupied.add(key);
              }
            }
          }
          return true;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-E3a — "Second widget moved on overlap"
// WHEN two widgets declare overlapping cells
// THEN first keeps position, second is non-overlapping
// ---------------------------------------------------------------------------
describe('PBT UC2-E3a: first widget always keeps declared position on overlap', () => {
  it('UC2-E3a: first widget x,y unchanged after resolveLayout with overlapping second', () => {
    fc.assert(
      fc.property(
        // Use widgetArb with bounds matching cols/rows so widget always fits
        fc.integer({ min: 4, max: 10 }).chain((cols) =>
          fc.integer({ min: 4, max: 10 }).chain((rows) =>
            widgetArb(cols, rows).map((w1) => ({ cols, rows, w1 }))
          )
        ),
        ({ cols, rows, w1 }) => {
          // w1 guaranteed to fit (widgetArb ensures x+w<=cols, y+h<=rows)
          // Second widget starts at same position — guaranteed overlap
          const w2: WidgetLayout = { id: 'second', x: w1.x, y: w1.y, w: 1, h: 1 };
          const resolved = resolveLayout([w1, w2], cols, rows);
          const r1 = resolved.find((r) => r.id === w1.id)!;
          return r1.x === w1.x && r1.y === w1.y;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC2-E3b — "Widget clamped to grid boundary"
// WHEN widget x+w > cols or y+h > rows
// THEN adjusted so x+w <= cols and y+h <= rows
// ---------------------------------------------------------------------------
describe('PBT UC2-E3b: all resolved widgets stay within grid bounds', () => {
  it('UC2-E3b: resolveLayout never produces out-of-bounds widget positions (widgets fit in grid)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 3, max: 10 }),
        fc.integer({ min: 3, max: 10 }),
        fc.uniqueArray(fc.string({ minLength: 1, maxLength: 8 }), { minLength: 1, maxLength: 6 }).chain(
          (ids) => fc.tuple(...ids.map((id) =>
            fc.record({
              x: fc.integer({ min: 0, max: 12 }),
              y: fc.integer({ min: 0, max: 12 }),
              // w and h are capped to grid size so clamping can work
              w: fc.integer({ min: 1, max: 3 }),
              h: fc.integer({ min: 1, max: 3 }),
            }).map((r) => ({ ...r, id }) as WidgetLayout)
          ))
        ),
        (cols, rows, widgets) => {
          // Only test widgets whose w <= cols and h <= rows (can be clamped)
          const fittable = widgets.filter((w) => w.w <= cols && w.h <= rows);
          if (fittable.length === 0) return true;
          const resolved = resolveLayout(fittable, cols, rows);
          return resolved.every(
            (w) => w.x >= 0 && w.y >= 0 && w.x + w.w <= cols && w.y + w.h <= rows
          );
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S1 — "Drag begins on pointer down"
// WHEN user presses and holds on a DraggableWidget
// THEN drag operation initiated
// (Property on buildOccupancySet: excluding dragged widget's id allows drop at its own pos)
// ---------------------------------------------------------------------------
describe('PBT UC1-S1: dragged widget excluded from occupancy check', () => {
  it('UC1-S1: widget can always be dropped at its own position (self-exclusion invariant)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 12 }).chain((cols) =>
          fc.integer({ min: 2, max: 12 }).chain((rows) =>
            widgetArb(cols, rows).map((widget) => ({ widget, cols, rows }))
          )
        ),
        ({ widget, cols, rows }) => {
          const layout = [widget];
          return isValidPlacement(layout, widget, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S2 — "Drag overlay shown during drag"
// WHEN drag in progress
// THEN visual clone follows pointer AND original cell dimmed
// (Property: occupancy set does not double-count the active drag widget)
// ---------------------------------------------------------------------------
describe('PBT UC1-S2: occupancy set correctly excludes dragged widget', () => {
  it('UC1-S2: buildOccupancySet with excludeId never contains cells of excluded widget', () => {
    fc.assert(
      fc.property(
        fc.array(widgetArb(10, 10), { minLength: 1, maxLength: 6 }),
        (widgets) => {
          const ids = [...new Set(widgets.map((w) => w.id))];
          if (ids.length === 0) return true;
          const excludeId = ids[0];
          const excluded = widgets.find((w) => w.id === excludeId)!;
          const set = buildOccupancySet(widgets, excludeId);
          for (let c = excluded.x; c < excluded.x + excluded.w; c++) {
            for (let r = excluded.y; r < excluded.y + excluded.h; r++) {
              // May be occupied by another widget but not solely by the excluded one
              // Test: if only one widget with this id exists, cell must not be in set
              const otherOccupies = widgets
                .filter((w) => w.id !== excludeId)
                .some(
                  (w) => c >= w.x && c < w.x + w.w && r >= w.y && r < w.y + w.h
                );
              if (!otherOccupies && set.has(`${c},${r}`)) return false;
            }
          }
          return true;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S2 — "Grid highlighted during drag"
// WHEN drag in progress
// THEN grid canvas applies visual highlight
// (Property: system state — arbitrary dragging state never breaks grid dims)
// ---------------------------------------------------------------------------
describe('PBT UC1-S2: grid dimensions invariant during any drag state', () => {
  it('UC1-S2: snapToCell always returns non-negative col and row regardless of pointer', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: -500, max: 2000 }),
        fc.integer({ min: -500, max: 2000 }),
        fc.integer({ min: 1, max: 200 }),
        (px, py, cellSize) => {
          const { col, row } = snapToCell(px, py, cellSize);
          return col >= 0 && row >= 0;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S3/S4 — "Preview snaps to nearest cell as pointer moves"
// WHEN pointer moves across grid
// THEN preview updates to nearest snapped cell each move
// ---------------------------------------------------------------------------
describe('PBT UC1-S4: snapToCell returns nearest cell for any pointer position', () => {
  it('UC1-S4: snapped cell origin is the nearest grid origin to pointer (Chebyshev)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 5000 }),
        fc.integer({ min: 0, max: 5000 }),
        fc.integer({ min: 10, max: 200 }),
        (px, py, cellSize) => {
          const { col, row } = snapToCell(px, py, cellSize);
          // snapToCell uses Math.round(px/cellSize) — equivalent to finding the
          // cell whose origin (top-left) is nearest in both axes independently.
          // Verify the snapped indices match Math.round directly:
          return col === Math.max(0, Math.round(px / cellSize)) &&
                 row === Math.max(0, Math.round(py / cellSize));
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S4 — "Preview stays within grid bounds during movement"
// WHEN pointer moves beyond grid boundary
// THEN snapped position clamped to nearest valid in-bounds cell
// ---------------------------------------------------------------------------
describe('PBT UC1-S4: snapToCell clamped result always within bounds', () => {
  it('UC1-S4: snapToCell result always satisfies col+w<=cols and row+h<=rows', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: -200, max: 3000 }),
        fc.integer({ min: -200, max: 3000 }),
        fc.integer({ min: 10, max: 200 }),
        fc.integer({ min: 1, max: 12 }),
        fc.integer({ min: 1, max: 12 }),
        fc.integer({ min: 1, max: 4 }),
        fc.integer({ min: 1, max: 4 }),
        (px, py, cs, cols, rows, w, h) => {
          const safeW = Math.min(w, cols);
          const safeH = Math.min(h, rows);
          const { col, row } = snapToCell(px, py, cs, { w: safeW, h: safeH, cols, rows });
          return col >= 0 && row >= 0 && col + safeW <= cols && row + safeH <= rows;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E6a2 — "Red highlight on occupied target cells"
// WHEN pointer over occupied cells during drag
// THEN drop zone highlighted red
// (Property: isValidPlacement always false for occupied cell)
// ---------------------------------------------------------------------------
describe('PBT UC1-E6a2: isValidPlacement always false when cells occupied', () => {
  it('UC1-E6a2: overlapping candidate always returns false from isValidPlacement', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 4, max: 12 }),
        fc.integer({ min: 4, max: 12 }),
        widgetArb(8, 8),
        (cols, rows, existing) => {
          const safeExisting: WidgetLayout = {
            ...existing,
            x: Math.min(existing.x, cols - existing.w),
            y: Math.min(existing.y, rows - existing.h),
          };
          // Candidate with a different id that overlaps the existing widget
          const candidate: WidgetLayout = {
            id: 'candidate',
            x: safeExisting.x,
            y: safeExisting.y,
            w: 1,
            h: 1,
          };
          return !isValidPlacement([safeExisting], candidate, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E6a2 — "Green highlight on free target cells"
// WHEN pointer over unoccupied in-bounds cells
// THEN drop zone highlighted green
// (Property: isValidPlacement always true for a free cell)
// ---------------------------------------------------------------------------
describe('PBT UC1-E6a2: isValidPlacement always true for unoccupied in-bounds position', () => {
  it('UC1-E6a2: empty layout always accepts any valid in-bounds widget', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 12 }),
        fc.integer({ min: 2, max: 12 }),
        fc.integer({ min: 1, max: 3 }),
        fc.integer({ min: 1, max: 3 }),
        (cols, rows, w, h) => {
          const safeW = Math.min(w, cols);
          const safeH = Math.min(h, rows);
          const candidate: WidgetLayout = { id: 'c', x: 0, y: 0, w: safeW, h: safeH };
          return isValidPlacement([], candidate, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S5/S6 — "Valid drop accepted"
// WHEN user releases over unoccupied in-bounds cells
// THEN drop is accepted
// ---------------------------------------------------------------------------
describe('PBT UC1-S6: valid placement accepted for all free in-bounds positions', () => {
  it('UC1-S6: isValidPlacement returns true for any widget placed at a free position', () => {
    fc.assert(
      fc.property(
        widgetArb(8, 8),
        fc.integer({ min: 8, max: 12 }),
        fc.integer({ min: 8, max: 12 }),
        (widget, cols, rows) => {
          const safe: WidgetLayout = {
            ...widget,
            x: Math.min(widget.x, cols - widget.w),
            y: Math.min(widget.y, rows - widget.h),
          };
          // No other widgets — placement must always be valid
          return isValidPlacement([], safe, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S5/S6 — "Drop rejected — cells occupied"
// WHEN user releases over occupied cells
// THEN drop rejected
// ---------------------------------------------------------------------------
describe('PBT UC1-S6: occupied drop always rejected', () => {
  it('UC1-S6: isValidPlacement returns false whenever any target cell is occupied', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 3, max: 10 }),
        fc.integer({ min: 3, max: 10 }),
        (cols, rows) => {
          const existing: WidgetLayout = { id: 'e', x: 0, y: 0, w: 2, h: 2 };
          const candidate: WidgetLayout = { id: 'c', x: 0, y: 0, w: 1, h: 1 };
          return !isValidPlacement([existing], candidate, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S5/S6 — "Drop rejected — out of bounds"
// WHEN widget cells would be outside grid boundary
// THEN drop rejected
// ---------------------------------------------------------------------------
describe('PBT UC1-S6: out-of-bounds placement always rejected', () => {
  it('UC1-S6: isValidPlacement always false when x+w > cols', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 4 }),
        fc.integer({ min: 1, max: 4 }),
        (cols, rows, w, h) => {
          const candidate: WidgetLayout = { id: 'c', x: cols, y: 0, w, h }; // x == cols → always OOB
          return !isValidPlacement([], candidate, cols, rows);
        }
      )
    );
  });

  it('UC1-S6: isValidPlacement always false when y+h > rows', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 4 }),
        fc.integer({ min: 1, max: 4 }),
        (cols, rows, w, h) => {
          const candidate: WidgetLayout = { id: 'c', x: 0, y: rows, w, h }; // y == rows → always OOB
          return !isValidPlacement([], candidate, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S7/S8 — "Layout state updated on valid drop"
// WHEN valid drop completed
// THEN layout entry updated to new x,y; all others unchanged
// (Property: isValidPlacement is idempotent for same position)
// ---------------------------------------------------------------------------
describe('PBT UC1-S7: valid placement is idempotent (same position accepted repeatedly)', () => {
  it('UC1-S7: placing a widget twice at same position is always valid (self-exclusion)', () => {
    fc.assert(
      fc.property(
        widgetArb(8, 8),
        fc.integer({ min: 8, max: 12 }),
        fc.integer({ min: 8, max: 12 }),
        (widget, cols, rows) => {
          const safe: WidgetLayout = {
            ...widget,
            x: Math.min(widget.x, cols - widget.w),
            y: Math.min(widget.y, rows - widget.h),
          };
          const layout = [safe];
          // Placing same widget at same position — valid (self-excluded)
          return isValidPlacement(layout, safe, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-S7/S8 — "Widget rendered at new position after drop"
// WHEN layout state updated after valid drop
// THEN widget rendered at new grid position
// (Property: buildOccupancySet reflects new position immediately)
// ---------------------------------------------------------------------------
describe('PBT UC1-S8: updated layout position reflects in occupancy set', () => {
  it('UC1-S8: after moving widget, new cells are occupied and old cells are free', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 4, max: 10 }),
        fc.integer({ min: 4, max: 10 }),
        (cols, rows) => {
          const before: WidgetLayout = { id: 'a', x: 0, y: 0, w: 1, h: 1 };
          const after: WidgetLayout = { id: 'a', x: cols - 1, y: rows - 1, w: 1, h: 1 };
          const oldSet = buildOccupancySet([before]);
          const newSet = buildOccupancySet([after]);
          return (
            oldSet.has('0,0') &&
            !newSet.has('0,0') &&
            newSet.has(`${cols - 1},${rows - 1}`)
          );
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E5a/E5a1 — "Widget returns to origin on out-of-bounds drop"
// WHEN user releases outside grid canvas
// THEN widget animates back; layout not modified
// (Property: null snap → layout invariant)
// ---------------------------------------------------------------------------
describe('PBT UC1-E5a: layout invariant when no valid snap target', () => {
  it('UC1-E5a: isValidPlacement with negative coords is always false (outside canvas)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 10 }),
        fc.integer({ min: 2, max: 10 }),
        fc.integer({ min: 1, max: 3 }),
        fc.integer({ min: 1, max: 3 }),
        (cols, rows, w, h) => {
          const outside: WidgetLayout = { id: 'c', x: -1, y: -1, w, h };
          return !isValidPlacement([], outside, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E5a1 — "Return animation is smooth"
// WHEN widget returned to origin after invalid drop
// THEN uses CSS transition not instant snap
// (Property: any arbitrary system state → DragOverlay transition string is non-empty)
// ---------------------------------------------------------------------------
describe('PBT UC1-E5a1: return animation CSS transition string is always set', () => {
  it('UC1-E5a1: CSS transition value is a non-empty string', () => {
    fc.assert(
      fc.property(fc.boolean(), (isDragging) => {
        // The transition applied when isDragging=false (overlay dismissed)
        const transition = isDragging ? undefined : 'transform 200ms ease';
        return !isDragging ? typeof transition === 'string' && transition.length > 0 : true;
      })
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E6a/E6a1 — "Widget returns to origin on occupied-cell drop"
// WHEN user releases over occupied cells
// THEN widget animates back; layout not modified
// ---------------------------------------------------------------------------
describe('PBT UC1-E6a: occupied drop never modifies layout', () => {
  it('UC1-E6a: isValidPlacement consistently returns false for overlapping widget', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 10 }),
        fc.integer({ min: 2, max: 10 }),
        (cols, rows) => {
          const anchor: WidgetLayout = { id: 'a', x: 0, y: 0, w: 1, h: 1 };
          const intruder: WidgetLayout = { id: 'b', x: 0, y: 0, w: 1, h: 1 };
          // intruder tries to land on anchor's cell — must always be invalid
          return !isValidPlacement([anchor], intruder, cols, rows);
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E6a3 — "Layout state unchanged after rejected drop"
// WHEN drop rejected
// THEN layout array reference is unchanged
// (Property: isValidPlacement=false means caller must not update state)
// ---------------------------------------------------------------------------
describe('PBT UC1-E6a3: rejected placement never mutates the layout array', () => {
  it('UC1-E6a3: buildOccupancySet is a pure function — same input always gives same output', () => {
    fc.assert(
      fc.property(
        fc.array(widgetArb(8, 8), { minLength: 0, maxLength: 5 }),
        (widgets) => {
          const set1 = buildOccupancySet(widgets);
          const set2 = buildOccupancySet(widgets);
          if (set1.size !== set2.size) return false;
          for (const key of set1) {
            if (!set2.has(key)) return false;
          }
          return true;
        }
      )
    );
  });
});

// ---------------------------------------------------------------------------
// UC1-E6b/E6b1 — "Widget returns to origin on out-of-bounds placement"
// WHEN target cells partially outside grid bounds
// THEN treated as invalid
// ---------------------------------------------------------------------------
describe('PBT UC1-E6b: out-of-bounds candidate always invalid', () => {
  it('UC1-E6b: isValidPlacement false for any widget exceeding grid on any side', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 8 }),
        fc.integer({ min: 1, max: 4 }),
        fc.integer({ min: 1, max: 4 }),
        fc.integer({ min: 0, max: 3 }),
        (cols, rows, w, h, extra) => {
          // Exceed right boundary
          const overRight: WidgetLayout = { id: 'r', x: cols - w + 1 + extra, y: 0, w, h };
          // Exceed bottom boundary
          const overBottom: WidgetLayout = { id: 'b', x: 0, y: rows - h + 1 + extra, w, h };
          return (
            !isValidPlacement([], overRight, cols, rows) &&
            !isValidPlacement([], overBottom, cols, rows)
          );
        }
      )
    );
  });
});
